apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mysql
            topologyKey: "kubernetes.io/hostname"
      containers: 
      - image: gokulkarthick/mediawiki:latest
        name: mediawiki
        ports:
        - containerPort: 80
          name: mediawiki
