apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      nodeName: pool-tusp902aw-3ewo5 #node name need to be changed
      containers: 
      - image: gokulkarthick/mediawiki:latest
        name: mediawiki
        ports:
        - containerPort: 80
          name: mediawiki
        volumeMounts:
          - mountPath: /var/www/html/mediawiki/LocalSettings.php
            name: mediawiki-localsettings
            subPath: LocalSettings.php
      volumes:
        - name: mediawiki-localsettings
          configMap:
            name: localsettings